// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPsj9cx0dMitb0WaqVj2Ha7RbOItiN6YQ',
    appId: '1:685626423223:android:bfd3aa16e581ec1885da32',
    messagingSenderId: '685626423223',
    projectId: 'flutter-chat-app-82d18',
    databaseURL: 'https://flutter-chat-app-82d18-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-82d18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPsDe2EvpcmepFvXNUtngTjuL0NfTabbw',
    appId: '1:685626423223:ios:3f28b3dce957511385da32',
    messagingSenderId: '685626423223',
    projectId: 'flutter-chat-app-82d18',
    databaseURL: 'https://flutter-chat-app-82d18-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-82d18.appspot.com',
    iosClientId: '685626423223-vf04bks15abfen0m4fi2rmvlr2fnv9bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
